Vehicle spawner
Theseus-Aegis/Olympus pull request #128
Opened 2020-06-07 02:38 UTC by JoramD0

**When merged this pull request will:**
- Add vehicle spawner
- Add entry in `featureOverview`

2020-06-07 04:08 UTC, JoramD0 commented on Olympus.Stratis/functions/fn_featureOverview.sqf
> +    <br/><img image='x\tacr\addons\images\olympus\feature\vehicleSpawn.jpg' width='300' height='350'/>
Currently has an issue with this image, it won't even work on a laptop (while the teleporter one from #127 works fine.

2020-06-07 18:20 UTC, jonpas commented on Olympus.Stratis/functions/fn_vehicleSpawner.sqf
> +                        _spawnedVehicle adDItemCargoGlobal ["ToolKit", 1];
```suggestion
                        _spawnedVehicle addItemCargoGlobal ["ToolKit", 1];
```

2020-06-07 18:30 UTC, jonpas requested changes

2020-06-07 18:30 UTC, jonpas commented on Olympus.Stratis/functions/fn_vehicleSpawner.sqf
> +                    if (count (crew _vehicle) == 0) then {
```suggestion
                    if ((crew _vehicle) isEqualTo []) then {
```

2020-06-07 18:30 UTC, jonpas commented on Olympus.Stratis/functions/fn_vehicleSpawner.sqf
> +            ["CUP_C_Golf4_kitty_Civ", "Golf"], // Tyrone made me do this
Remove. :dagger:

2020-06-07 18:30 UTC, jonpas commented on Olympus.Stratis/functions/fn_vehicleSpawner.sqf
> +            ["tacs_Arcadian_B_Black", "Arcadian GT (Black)"],
Why do you need a fancy name, read it from the config by classname.

2020-06-07 18:30 UTC, jonpas commented on Olympus.Stratis/functions/fn_vehicleSpawner.sqf
> +createMarker ["vehicleSpawnerMarker", _controller];
Needs to be prefixed.

2020-06-07 19:44 UTC, JoramD0 commented on Olympus.Stratis/functions/fn_featureOverview.sqf
> +    <br/><img image='x\tacr\addons\images\olympus\feature\vehicleSpawn.jpg' width='300' height='350'/>
Solved, it was a corrupted image (please never use paint again @TyroneMF)

2020-06-08 09:26 UTC, jonpas approved these changes

2020-06-08 11:34 UTC, Mike-MF approved these changes

2020-06-23 15:15 UTC, merged