Add Shooting Range
Theseus-Aegis/Olympus pull request #152
Opened 2021-03-31 10:07 UTC by TyroneMF

- Adds a shooting range at 200m, 400m, 600m, 800m & 1000m.
- Based next to the airfield pointing out to sea.

2021-03-31 14:52 UTC, JoramD0 requested changes

2021-03-31 14:52 UTC, JoramD0 commented on Olympus.Stratis/mission.sqm
> +							type="Land_i_Addon_03_V1_F";
I'd prefer something military looking since it is on a military base

2021-03-31 14:52 UTC, JoramD0 commented on Olympus.Stratis/mission.sqm
> +									dataType="Layer";
Unlock all "Objects" & "Targets" groups

2021-04-01 00:37 UTC, TyroneMF commented
Removed the civilian building, it's military but i have no idea what else to do with it so.

![107410_20210401013239_1](https://user-images.githubusercontent.com/29175040/113227387-82a62200-928a-11eb-9550-5c33c6367ef1.png)

2021-04-19 18:09 UTC, JoramD0 approved these changes

2021-04-22 16:14 UTC, merged